In [1]:
#creating numpy/n-d arrays
import numpy as np

In [2]:
#creates 1D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
#creates 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#creates array with zeroes
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#creates array with ones
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:

arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
#Numpy array properties & attributes
arr1.shape

(5,)

In [16]:
arr2.shape

(2, 3)

In [19]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
arr9.shape

(2, 2, 2)

In [21]:
arr9.ndim

3

In [22]:
# give itemsize of type: ex: int, float etc..
arr9.itemsize

4

In [23]:
arr8.dtype

dtype('float64')

In [24]:
#converts data type to given dtype
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [25]:
#Numpy array vs Python Lists
#Faster
#Convenient
#Less Memory
lista = range(100)
arr11 = np.arange(100)


In [26]:
import sys

In [27]:
print(sys.getsizeof(87)*len(lista))

2800


In [28]:
print(arr11.itemsize * arr11.size)

400


In [31]:
#Indexing, Slicing and Iteration
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [34]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [41]:
arr12[4:6,2:5]

array([[18, 19],
       [22, 23]])

In [42]:
#Iteration
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
#prints all items in the array item by item
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [44]:
#Numpy operations
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])


In [45]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [46]:
arr1 * arr2 #vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [47]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [49]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [51]:
arr3 ,arr4

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [52]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [53]:
arr1.dot(arr2)

154

In [55]:
arr4.max(), arr4.min()

(11, 6)

In [56]:
arr4.min(axis=0) # minimum column wise

array([6, 7])

In [57]:
arr4.min(axis=1) # minimum row wise

array([ 6,  8, 10])

In [59]:
arr4.sum(axis=0) # sum column wise

array([24, 27])

In [60]:
arr4.mean()

8.5

In [61]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [62]:
arr4.std() # standard deviation

1.707825127659933

In [63]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [64]:
np.median(arr4)

8.5

In [65]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [67]:
#Fancy indexing
arr8 = np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])